name: LP dev image build workflow

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Build the LP dev LXD image
      run: |
        echo "Installing LXD image builder"
        sudo snap install --edge --classic lxd-imagebuilder 
        sudo add-apt-repository -y universe
        sudo apt -y update
        sudo apt -y install debootstrap
        snap list
        echo "Cloning Launchpad"
        git clone --progress --verbose -b master https://git.launchpad.net/launchpad
        cd launchpad
        echo "Create LXD image for Launchpad"
        make build-lxd-image
        ls -la
        FILE_PATH=$(realpath $(ls ubuntu-*.tar.xz | head -n 1))
        echo "File found: $FILE_PATH"
        echo "file_path=$FILE_PATH" >> $GITHUB_ENV

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.file_path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
