# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run Bash Commands
      run: |
        # Place your commands here
        echo "Installing LXD image builder"
        sudo snap install --edge --classic lxd-imagebuilder 
        sudo add-apt-repository -y universe
        sudo apt -y update
        sudo apt -y install debootstrap
        snap list
        echo "Cloning Launchpad"
        git clone -b master https://git.launchpad.net/launchpad
        cd launchpad
        echo "Create LXD image for Launchpad"
        make build-lxd-image
        ls -la

    - name: Find Tar File
      id: find_tar
      run: |
        FILE_PATH=$(ls ubuntu-*.tar.xz | head -n 1)
        echo "File found: $FILE_PATH"
        echo "file_path=$FILE_PATH" >> $GITHUB_ENV

    - name: Upload Tar File as GitHub Artifact
      uses: actions/upload-artifact@v3
      with:
        name: lpdev-lxd-image
        path: ${{ env.file_path }}
