# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run Bash Commands
      run: |
        # Place your commands here
        echo "Installing LXD image builder"
        sudo snap install lxd-imagebuilder --classic
        snap list
        echo "Cloning Launchpad"
        git clone https://git.launchpad.net/launchpad
        cd launchpad
        echo "Create LXD image for Launchpad"
        make build-lxd-image
        ls -la
